### ISSUE TITLE
Vaše připojení není zabezpečené

### ISSUE THREAD

**Issue by ollesmaps** [JasnaPaka/wpcity#123]
Odtud - 2. odkaz

https://www.google.cz/search?q=Obrazy+ze+s%C3%A9rie+Worthless&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&dcr=1&ei=lCx_WoKqCKuF8Qe9lKnQDg

Sem - 

![nebez](https://user-images.githubusercontent.com/20535899/36064796-f9aab504-0e90-11e8-90fd-bda5a276caf7.jpg)

**Comment by JasnaPaka** [comment]
Upravil jsem generování certifikátu, aby bral vybrané subdomény. Nyní by u nás mělo https:// fungovat v pořádku. Opravil jsem i odkazy v šabloně, které vedly natvrdo na http://. Pokud nebudou s https:// problémy, můžeme časem přehodit natvrdo provoz na https://.
