### ISSUE TITLE
Titul před jménem

### ISSUE THREAD

**Issue by ollesmaps** [JasnaPaka/wpcity#165]
Jsem pro nedávání titulů před a za jméno. Můžeme je evidovat, ale k autorovi bych je nedával. Je to mnohdy nedohledatelné, zatím to máme u málokoho a působí to nepatřičně. Tituly - so Rakousko-Uhersko...

**Comment by JasnaPaka** [comment]
Dobře, dáme to pryč.

**Comment by JasnaPaka** [comment]
Vyřešeno.
